name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Build app
      run: |
        yarn install --frozen-lockfile
        yarn build
        sed -i 's/src="\(.*\)"/src="https:\/\/jedluk.github.io\/hexifier\1"/'
        sed -i 's/href="\(.*\)"/src="https:\/\/jedluk.github.io\/hexifier\1"/'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist