name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  APP_URL: https://jedluk.github.io/hexifier/

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Build app
      run: |
        yarn install --frozen-lockfile
        yarn build
        sed -i 's|src="\/\{0,1\}\(.*\)"|src="'$APP_URL'\1"|g' index.html
        sed -i 's|href="\/\{0,1\}\(.*\)"|href="'$APP_URL'\1"|g' index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist